# PubMed Literature Push 配置文件样例
# 这是最新版本的配置文件，支持用户组、多发件邮箱、LLM提供商等高级功能

# === 重要说明：LLM提供商配置注意事项 ===
#
# 1. OpenAI提供商：
#    - 支持官方API和自定义端点（通过base_url参数）
#    - 自定义端点必须兼容OpenAI API格式
#
# 2. Gemini提供商：
#    - 仅支持官方Google API，不支持自定义端点（Google官方库限制）
#    - 如果需要通过代理访问，请使用环境变量HTTPS_PROXY或调用LLMService.configure_proxy()
#
# 3. 自定义提供商：
#    - 必须提供api_endpoint，且端点必须支持OpenAI兼容格式
#    - 对于Gemini模型的自定义端点，需要通过OpenAI兼容的代理服务访问
#    - 系统会自动检测模型名称中包含"gemini"的情况，并给出相应警告
#
# === 配置示例 ===

# 调度器设置
scheduler:
  run_time: '08:00'                     # 每日运行时间 (24小时格式)
  delay_between_keywords_sec: 60        # 关键词任务间隔（秒）

# PubMed 搜索设置
pubmed:
  max_articles: 50                      # 每个关键词最大文章数量

# 代理设置（可选）
# 如果需要通过代理访问API，可以在代码中调用 LLMService.configure_proxy("http://proxy:port")
# 或者设置环境变量 HTTPS_PROXY 和 HTTP_PROXY
# 注意: 对于Gemini API，代理是访问官方API的唯一方式

# LLM 提供商配置
llm_providers:
  - name: openai                        # 提供商名称（用于任务映射）
    provider: openai                    # 提供商类型: openai, gemini, custom
    api_key: sk-your-openai-api-key     # API密钥
    api_endpoint: ''                    # 自定义接入点（可选，openai支持自定义端点）
  
  - name: gemini                        # Gemini提供商示例
    provider: gemini
    api_key: your-gemini-api-key
    api_endpoint: ''                    # 注意: Gemini不支持自定义端点，此字段将被忽略
  
  - name: custom_openai                 # 自定义OpenAI兼容端点示例
    provider: custom
    api_key: sk-custom-api-key
    api_endpoint: https://your-custom-endpoint.com/v1  # 必须是OpenAI兼容格式
  
  - name: custom_gemini_proxy           # Gemini代理服务示例
    provider: custom
    api_key: sk-custom-api-key
    api_endpoint: https://your-gemini-proxy.com/v1    # 必须是OpenAI兼容格式
    # 注意: 由于Google官方库限制，连接Gemini需要通过OpenAI兼容的代理服务

# 任务模型映射
task_model_mapping:
  query_generator:                      # 检索词生成器
    provider_name: openai               # 使用的提供商名称（对应llm_providers中的name）
    model_name: gpt-4o-mini            # 模型名称
  
  summarizer:                           # 综述生成器
    provider_name: gemini              # 使用官方Gemini API
    model_name: gemini-1.5-flash        # Gemini模型名称
  
  abstract_translator:                  # 摘要翻译器
    provider_name: custom_openai        # 使用自定义OpenAI兼容端点
    model_name: qwen2.5-72b-instruct    # 模型名称
  
  # 示例：使用Gemini代理服务
  # alternative_summarizer:
  #   provider_name: custom_gemini_proxy  # 使用Gemini代理服务
  #   model_name: gemini-pro             # 模型名称

# 翻译设置
translation_settings:
  batch_size: 20                        # 批处理大小
  delay_between_batches_sec: 5          # 批次间隔（秒）

# 提示词配置
prompts:
  generate_query: "# 任务：生成高级PubMed文献检索式\n\n## 1. 角色与目标\n你将扮演一位资深的生物医学文献检索专家，你的核心目标是根据用户提供的关键词 `{keyword}` 和日期范围 `{date_query}`，构建一个专业、高效、结构化的PubMed高级检索式，以在保证高召回率的同时，实现最高的精确率。\n\n## 2. 背景与上下文\n- 用户提供的核心检索词为：`{keyword}`\n- 用户指定的文献日期范围为：`{date_query}`\n\n## 3. 关键步骤\n在你的创作过程中，请遵循以下内部步骤来构思和打磨作品：\n1.  **概念识别与标准化**: 分析用户关键词 `{keyword}`，识别出其中的核心生物医学概念。如果关键词为非英语，需将其翻译为标准的学术英语。\n2.  **概念扩展与同义词构建**: 针对每个核心概念，执行以下操作：\n    - 查找对应的官方MeSH主题词 (Medical Subject Headings)。为了提升精确度，优先考虑使用 `[Major Topic]` 标签。\n    - 收集常见的同义词、缩写、变体及相关术语。为了提升精确度，优先将核心术语限定在 `[Title]` 字段进行检索。\n    - **增加排他性以消除歧义**: 识别常用缩写或术语在文献中可能存在的、与当前主题无关的明确含义。使用 `NOT` 运算符将这些无关概念排除。例如，当检索缩写"TB"代表结核病时，应主动排除其作为"transit bipartition"（一种外科手术）或"Terbium"（一种化学元素）的含义。\n    - 使用 `OR` 逻辑运算符将MeSH词与所有同义词组合成一个概念组，并用括号包裹。包含歧义的术语应在内部使用 `NOT` 进行限定，例如 `(... OR (\"TB\"[Title] NOT (\"transit bipartition*\" OR \"Terbium\")) OR ...)`。\n3.  **检索式结构化组合**: 如果存在多个独立的核心概念，使用 `AND` 逻辑运算符将各个概念组连接起来，形成完整的主题检索部分。\n4.  **整合日期并最终定稿**: 将构建好的主题检索部分与用户提供的日期范围 `{date_query}` 使用 `AND` 运算符连接，形成最终的完整检索式。\n\n## 4. 输出要求\n- **格式**: 纯文本字符串 (Plain Text String)。\n- **风格**: 技术性、高度精确、符合PubMed语法规范。\n- **约束**:\n    - 输出内容必须是单一、完整且语法正确的PubMed检索式。\n    - 不得包含任何解释、注释、代码块标记或其他非检索式本身的文本。\n    - **最终输出**: 你的最终回复应仅包含最终成果本身，不得包含任何步骤说明、分析或其他无关内容。"

  generate_review: "# 任务：撰写关于"{keyword}"的专业医学文献综述\n\n## 1. 角色与目标\n你将扮演一位资深医学研究员，专长于撰写高质量的文献综述。你的核心目标是，基于提供的一系列关于"{keyword}"的文献摘要，撰写一篇约500-800字的、结构清晰、逻辑严谨的中文文献综述，精准整合并提炼所有来源的核心发现。\n\n## 2. 背景与上下文\n你将收到一系列关于特定主题"{keyword}"的医学文献摘要。这些摘要是撰写综述的唯一信息来源。每篇摘要前会有一个唯一的文献编号，如`[1]`、`[2]`等，用于在综述正文中进行引用。\n\n**文献列表:**\n{articles_text}\n\n## 3. 关键步骤\n在你的创作过程中，请遵循以下内部步骤来构思和打磨作品：\n1.  **筛选与提炼**: 首先，评估每篇文献摘要与核心主题"{keyword}"的直接相关性。忽略或排除那些与主题明显无关的文献。然后，对于所有相关的文献，仔细阅读并分析其摘要，识别其核心研究问题、关键发现和主要结论。为每篇相关摘要标记出1-2个最重要的信息点。\n2.  **主题归纳与结构设计**: 比较所有相关摘要的核心信息点，寻找它们之间的共性、差异性或关联性。根据这些关联，将信息点归纳为2-3个核心主题（例如：病理机制、治疗方法、预后影响等），并以此为基础设计综述的逻辑结构（引言、主体段落、结论）。\n3.  **撰写与整合**: 按照设计的结构撰写综述正文。在论述每个主题时，流畅地将来自不同文献的信息整合在一起，进行比较、对比或补充说明，确保行文连贯。\n4.  **引用与审校**: 在引用具体信息时，必须在句末或适当位置使用 `[文献编号]` 格式进行标注。完成后，通读全文，检查逻辑的严密性、语言的专业性以及引用格式的准确性。\n\n## 4. 输出要求\n- **格式**: 纯文本格式的综述正文。\n- **风格**: 专业、客观、学术化的医学写作风格，语言精炼、逻辑严密。\n- **约束**:\n    - 必须整合所有**与主题相关的**文献的关键信息，确保没有任何一篇相关文献被遗漏，并在此基础上形成有逻辑的论述。严禁简单地逐篇罗列摘要内容。\n    - 在正文中引用信息来源时，必须使用 `[文献编号]` 的格式。\n    - **最终输出**: 你的最终回复应仅包含综述正文本身，不得包含任何标题、参考文献列表、分析过程或其他额外说明。"

  translate_abstract: "# 任务：批量英文学术摘要翻译\n\n## 1. 角色与目标\n你将扮演一位**资深学术翻译专家**，精通中英双语，尤其擅长将前沿科技领域的英文文献翻译成专业、严谨、流畅的中文。你的核心目标是**将一批英文学术摘要精准地翻译成符合中文学术规范的专业译文**。\n\n## 2. 背景与上下文\n待翻译的英文摘要将通过占位符 `{abstracts_batch}` 传入，其中可能包含多篇摘要，并使用 `|||---|||` 作为分隔符。你需要处理这批数据，并以相同的格式输出结果。\n\n## 3. 关键步骤\n在你的翻译过程中，请遵循以下内部步骤来构思和打磨作品：\n1.  **解析与理解**: 逐篇阅读英文摘要，完全理解其研究背景、方法、核心发现和结论。识别并锁定关键的专业术语和固定搭配。\n2.  **精准翻译初稿**: 基于理解，进行直译和意译相结合的翻译，确保所有信息点被完整、准确地转换到中文，并保持原文的逻辑结构。\n3.  **学术化润色**: 审校中文译稿，将语言调整为书面化的学术风格。确保用词专业、严谨，语句通顺、流畅，符合中文学术界的表达习惯。\n4.  **格式化整合**: 将所有翻译完成的摘要，按照原始顺序排列，并使用 `|||---|||` 作为唯一的分隔符进行拼接，准备最终输出。\n\n## 4. 输出要求\n- **格式**: 纯文本。多篇摘要译文之间使用 `|||---|||` 分隔。\n- **风格**: 专业、严谨、流畅的学术语言。\n- **约束**:\n    - 必须严格保持摘要的原始顺序。\n    - 译文必须忠实于原文，不得增删信息或进行主观解读。\n    - 如果遇到多义词，应根据上下文选择最符合学术语境的释义。\n    - **最终输出**: 你的最终回复应仅包含翻译后的摘要文本本身，并使用 `|||---|||` 分隔。禁止包含任何标题、前言、解释、分析或任何其他无关内容。\n\n---\n**英文原文输入:**\n{abstracts_batch}"

# SMTP 邮件设置
smtp:
  max_retries: 3                        # 最大重试次数
  retry_delay_sec: 300                  # 重试延迟（秒）
  base_interval_minutes: 10             # 基础间隔（分钟）
  admin_email: admin@example.com        # 管理员邮箱（接收系统报告）
  
  # 发件邮箱账号配置（支持多个邮箱轮替发送）
  accounts:
    - server: smtp.gmail.com            # SMTP服务器
      port: 587                         # 端口
      username: your-email@gmail.com    # 邮箱用户名
      password: your-app-password       # 邮箱密码或应用专用密码
      sender_name: PubMed Literature Push # 发件人名称
    
    - server: smtp.outlook.com          # 第二个邮箱示例
      port: 587
      username: your-email@outlook.com
      password: your-password
      sender_name: Medical Research Updates
    
    - server: smtp.qq.com               # 国内邮箱示例
      port: 465
      username: 1234567@qq.com
      password: your-auth-code
      sender_name: 医学文献推送

# 用户组配置
user_groups:
  - group_name: 结核病研究团队             # 用户组名称
    emails:                             # 组内用户邮箱列表
      - researcher1@university.edu
      - researcher2@hospital.org
      - student@grad.school.edu
    keywords:                           # 共享的关键词列表
      - 结核病
      - 肺结核
      - 抗结核治疗
  
  - group_name: 心血管疾病科室
    emails:
      - doctor1@cardiology.com
      - doctor2@cardiology.com
      - nurse@cardiology.com
    keywords:
      - 冠心病
      - 心肌梗死
      - 心脏支架
      - 高血压
  
  - group_name: 肿瘤研究组
    emails:
      - oncologist@cancer-center.org
      - researcher@cancer-lab.edu
    keywords:
      - 肺癌
      - 免疫治疗
      - 靶向治疗
      - CAR-T细胞